SELECT
ST.Pos AS PositionName,
ST.Comp AS LeagueName,
ST.Squad AS TeamName,
ST.Nation AS NationName,
ST.[born] + left(replace(convert(varchar,convert(datetime,'2021-11-28')-(convert(int,right(ST.[age],charindex('-',ST.[age])))),101),'/',''),4) as [BornDateKey],
ST.Season AS Season,
ST.Player AS PlayerName,
CONVERT(int,ST.MP) AS MatchesPlayed,
CONVERT(int,ST.Starts) AS MatchesStarts,
CONVERT(float,ST.Min) AS MatchesMinutes,
CONVERT(int,ST.Gls) AS Goals,
CONVERT(int,ST.Ast) AS Assist,
CONVERT(int,ST.PK) AS PkGoals,
CONVERT(int,ST.Pkatt) AS PkAttempted,
CONVERT(int,ST.CrdY) AS YellowCards,
CONVERT(int,MS.CrdY_2) AS YellowCardsSecond,
CONVERT(int,ST.CrdR) AS RedCards,
CONVERT(float,ST.xG) AS xG,
CONVERT(float,ST.npXG) AS npXG,
CONVERT(float,ST.xA) AS xA,
CONVERT(int,S.sH) AS ShotsTotal,
CONVERT(int,S.SoT) AS ShotsOnTarget,
CONVERT(int,S.FK) AS FreeKicks,
CONVERT(int,PA.Cmp_Total) AS TotalPassesCompleted,
CONVERT(int,PA.Att_Total) AS TotalPassesAttempted,
CONVERT(int,PA.TotDist) AS TotalDistance,
CONVERT(int,PA.PrgDist) AS TotalProgressiveDistance,
CONVERT(int,PA.Cmp_Short) AS ShortPassesCompleted,
CONVERT(int,PA.Att_Short) AS ShortPassesAttempted,
CONVERT(int,PA.Cmp_Medium) AS MediumPassesCompleted,
CONVERT(int,PA.Att_Medium) AS MediumPassesAttempted,
CONVERT(int,PA.Cmp_Long) AS LongPassesCompleted,
CONVERT(int,PA.Att_Long) AS LongPassesAttempted,
CONVERT(int,PA.KP) AS KeyPasses,
CONVERT(int,PA._1_3) AS CompletedPassesAttackingArea,
CONVERT(int,PA.PPA) AS CompletedPassesPenaltyArea,
CONVERT(int,PA.CrsPA) AS CompletedCrossesPenaltyArea,
CONVERT(int,PT.Live) AS LiveBallPasses,
CONVERT(int,PT.Dead) AS DeadBallPasses,
CONVERT(int,PT.FK) AS FreeKicksPassesAttempted,
CONVERT(int,PT.TB) AS BetweenDefendersPassesCompleted,
CONVERT(int,PT.Press) AS PassesUnderPressure,
CONVERT(int,PT.Crs) AS Crosses,
CONVERT(int,PT.CK) AS CornerKicks,
CONVERT(int,PT.Left_Foot) AS LeftFootPassesAttempted,
CONVERT(int,PT.Right_Foot) AS RightFootPassesAttempted,
CONVERT(int,PT.Head) AS HeadPassesAttempted,
CONVERT(int,PT.Offsides) AS Offsides,
CONVERT(int,DA.Tkl) AS Tackle,
CONVERT(int,DA.TklW) AS TackleWon,
CONVERT(int,DA.Def_3rd_Tackles) AS DefensiveAreaTackle,
CONVERT(int,DA.Mid_3rd_Tackles) AS MiddleAreaTackle,
CONVERT(int,DA.Att_3rd_Tackles) AS AttackingAreaTackle,
CONVERT(int,DA.Tkl_vs_Dribbles) AS TackleWSDribblers,
CONVERT(int,DA.Press) AS TotalPress,
CONVERT(int,DA.Def_3rd_Press) AS DefensiveAreaPress,
CONVERT(int,DA.Mid_3rd_Press) AS MiddleAreaPress,
CONVERT(int,DA.Att_3rd_Press) AS AttackingAreaPress,
CONVERT(int,DA.Blocks) AS Blocks,
CONVERT(int,DA.Interceptions) AS Interceptions,
CONVERT(int,DA.Clr) AS Clearances,
CONVERT(int,PO.Touches) AS TotalTouchesBall,
CONVERT(int,PO.Live) AS TotalTouchesLiveBall,
CONVERT(int,PO.Def_3rd) AS DefensiveAreaTouches,
CONVERT(int,PO.Mid_3rd) AS MiddleAreaTouches,
CONVERT(int,PO.Att_3rd) AS AttackingAreaTouches,
CONVERT(int,PO.Att_Pen) AS PenaltyAreaTouches,
CONVERT(int,PO.Att_Dribbles) AS DribblesAttempted,
CONVERT(int,PO.Succ_Dribbles) AS DribblesSuccessfully,
CONVERT(int,PO.Number_of_Players_Dribbled_Past) AS PlayersDribbledPast,
CONVERT(int,PO.Megs) AS BallBetweenLeg,
CONVERT(int,PO.Carries) AS Carries,
CONVERT(int,PO.TotDist) AS TotalCarriesDist,
CONVERT(int,PO.PrgDist) AS ProgressiveDist,
CONVERT(int,PO.CPA) AS CarriesIntoPenaltyArea,
CONVERT(int,MS.Fls) AS FoulsCommitted,
CONVERT(int,MS.Fld) AS FoulsDrawn,
CONVERT(int,MS.Pkwon) AS PenaltyKicksWon,
CONVERT(int,MS.OG) AS OwnGoals,
CONVERT(int,MS.Aerials_Won) AS AerialDuelsWon,
CONVERT(int,MS.Aerials_Lost) AS AerialDuelsLost,
CONVERT(int,GK.GA) AS GoalAgainst,
CONVERT(int,GK.SoTA) AS ShotsOnTargetAgainst,
CONVERT(int,GK.Saves) AS Saves,
CONVERT(int,GK.W) AS Wins,
CONVERT(int,GK.D) AS Draws,
CONVERT(int,GK.L) AS Losses,
CONVERT(int,GK.CS) AS CleanSheets,
CONVERT(int,GK.PKatt) AS PenaltyKicksAttempted,
CONVERT(int,GK.PKA) AS PenaltyKicksAllowed,
CONVERT(int,GK.PKsv) AS PenaltyKicksSaved,
CONVERT(int,GK.PKm) AS PenaltyKicksMissed,
CONVERT(float,GA.PSxG) AS PostShotXG
FROM [dbo].[STG_Standard_Stats] ST 
INNER JOIN [dbo].[STG_Shooting] S ON ST.Season+ST.Player+ST.Squad = S.Season+S.Player+S.Squad
INNER JOIN [dbo].[STG_Possession] PO ON ST.Season+ST.Player+ST.Squad = PO.Season+PO.Player+PO.Squad 
INNER JOIN [dbo].[STG_Playing_Time] PTI ON ST.Season+ST.Player+ST.Squad = PTI.Season+PTI.Player+PTI.Squad
INNER JOIN [dbo].[STG_Passing] PA ON ST.Season+ST.Player+ST.Squad = PA.Season+PA.Player+PA.Squad
INNER JOIN [dbo].[STG_Pass_Types] PT ON ST.Season+ST.Player+ST.Squad = PT.Season+PT.Player+PT.Squad
INNER JOIN [dbo].[STG_Miscellaneous_Stats] MS ON ST.Season+ST.Player+ST.Squad = MS.Season+MS.Player+MS.Squad
INNER JOIN [dbo].[STG_Goal_Shot_Creation] GSC ON ST.Season+ST.Player+ST.Squad = GSC.Season+GSC.Player+GSC.Squad
INNER JOIN [dbo].[STG_Defensive_Action] DA ON ST.Season+ST.Player+ST.Squad = DA.Season+DA.Player+DA.Squad
LEFT JOIN  [dbo].[STG_Goalkeeping_Advanced]  GA ON ST.Season+ST.Player+ST.Squad = GA.Season+GA.Player+GA.Squad
LEFT JOIN  [dbo].[STG_Goalkeeping] GK ON ST.Season+ST.Player+ST.Squad = GK.Season+GK.Player+GK.Squad
WHERE ST.Nation != ''